# Site
repository: Opiyo-5678/portfolio_machine_learning

# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Austine Opiyo
title: Machine Learning Engineer | AI Developer
email: austineopiyo84@gmail.com
# email_title: Email (Email title override)
phone: +254 113449850
# phone_title: Phone (Phone title override)
website: https://github.com/Opiyo-5678/portfolio_machine_learning
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: Austine622630
github_username:  https://github.com/Opiyo-5678
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
facebook_username: https://www.facebook.com/profile.php?id=100075290277507
#flickr_username: jekyll
#instagram_username: Austine_Opiyo
linkedin_username: https://www.linkedin.com/in/austine-opiyo-38b77a293/
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#orcid_username: 0000-0000-0000-0000
#googlescholar_username: Austine Opiyo

# Additional icon links
#additional_links:
- #title: Link name
  #icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
 # url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image:  images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
    Passionate Machine Learning Engineer with expertise in developing AI solutions for real-world problems. Specialized in time-series forecasting, computer vision, and deploying scalable ML models.
    Key strengths:
  - Strong Python programming skills
  - Experience with TensorFlow/PyTorch
  - Data preprocessing and feature engineering
  - Cloud deployment (AWS/GCP)
  - End-to-end project implementation
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        #border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
    -name: "Nairobi Air Quality Prediction System"
    description: "Machine learning solution for urban pollution monitoring and forecasting"
    highlights:
    - "Developed production-ready ETS time-series model with 85% prediction accuracy (20% improvement over baseline)"
    - "Engineered critical temporal features: 7-day rolling averages, holiday indicators, and meteorological lag variables"
    - "Built end-to-end pipeline from raw sensor data to actionable insights via Flask API"
    - "Visualized high-risk pollution zones for Nairobi County officials using interactive Folium maps"
    github_link: "https://github.com/Opiyo-5678/nairobi_air_prediction"
    tags:
    - "Python"
    - "Time-Series Forecasting"
    - "Flask API"
    - "Environmental AI"
    - "Data Storytelling"
    additional_links:
    - title: GitHub Repository
      icon: fab fa-github
      url: https://github.com/Opiyo-5678/nairobi_air_prediction
    - title: Technical Documentation
      icon: fas fa-file-alt
      url: https://github.com/Opiyo-5678/nairobi_air_prediction/blob/main/README.md
    quote: "Transforming sensor data into public health decisions"
    description: |
     **Core Innovation:**  
    - First open-source air quality model specifically calibrated for Nairobi's unique topography and pollution patterns  
    
     **Technical Achievements:**  
    - Reduced prediction error by 35% through custom seasonal decomposition  
    - Automated data validation pipeline handling 15,000+ hourly sensor readings  
    - Dockerized deployment for cloud scalability (AWS ECS compatible)
  - name: "Mataagari Ventures - Automotive Lighting E-commerce"
    description: "Online store specializing in premium vehicle lighting solutions (headlights, taillights, fog lights, LED bars)."
    highlights:
    - "Built a high-conversion WooCommerce store with customized product filters for vehicle compatibility (make/model/year)."
    - "Implemented SEO optimization that increased organic traffic by 40% for 'car LED headlights Kenya' searches."
    - "Integrated MPesa payment gateway with automated receipt generation, reducing checkout friction by 35%."
    - "Developed interactive product comparison tools helping customers choose between halogen/Xenon/LED options."
    link: "https://mataagariventures.co.ke/"
    link_text: "Live Store"
    tags:
    - "E-commerce"
    - "WooCommerce"
    - "Automotive Tech"
    - "SEO"
    - "Payment Gateways"
  # - title: Experience
  #   layout: list
  #   content:
  #     - layout: right
  #       title: Company name
  #       sub_title: Job title
  #       caption: Date Range (eg. November 2016 - present)
  #       link: Link to company (optional)
  #       quote: >
  #         Short description of the company (optional)
  #       description: | # this will include new lines to allow paragraphs
  #         Description of role
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Pwani University
        sub_title: BSc in Computer Science | Machine learning & AI Focus
        caption: 2021 - 2025
        quote: >
          Machine Learning, Data Structures, Algorithms
       # description: | # this will include new lines to allow paragraphs
         # Description of qualification
  - title: Technical Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
          **Machine Learning**: Python, TensorFlow, PyTorch, Scikit-learn, Time-Series Forecasting  
          **Data Engineering**: Pandas, NumPy, SQL, Data Visualization  
          **Backend Development**: Flask, REST APIs, Docker  
          **Cloud Platforms**: AWS, GCP (Basic)  
          **Tools**: Git, Jupyter Notebooks, Linux
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
- jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
